### PR TITLE
binary downloads for articles

### PR DESCRIPTION
**Pull request by ellduin**
added divs and code to parse information about additional files that are not generated prgs

### CODE REVIEW

**Comment by ellduin** [comment]
should there be code to check if all files in the prg folder are used at some point?

what should the actual titles of the supervoc and lehrerkalender demo files be? "Beispiel-Datenbank" and "Beispiel" currently

i am adding a "Servicekassette" (via a data-source tag in the scribing div) after the descriptive file name - i am unsure about that? keep? or reframe? leave out? without explanation it seems weird but Servicediskette is maybe not that much better :D 

Screenshot 2024-05-16 at 16 33 46

**Comment by mist64** [comment]
I don't think we need any additional info on the source of the additional file.

**Comment by ellduin** [comment]
removed the Servicedisketten part

**Comment by ellduin** [comment]
also marked underground listings as local so they do not show up in the downloads (there it shows the complete program from the Programmservicediskette)

**Pull request merged**
