### PR TITLE
Start adding tables

### PR DESCRIPTION
**Pull request by thierer**
This PR is just meant as a quick heads-up that I started adding some of the TODOs. I'd suggest you don't merge it just yet and I'll keep updating this branch.

I have some questions, though:

- Seems you never use `<thead>`, though it has styles defined? I've used it in some places, because I thought it looked nicer. I can make these plain tables again, no problem.
- You also don't seem to use `<br/>` in tables. Are they frowned upon?
- I don't really like the look of the "Die Bedeutungen der Gerätenummern" tables in "Komfortables Treiberprogramm für Centronics-Drucker". (But the layout of the printed table is weird, too, imho). Do you have any suggestion?

### CODE REVIEW

**Comment by mist64** [comment]
> * Seems you never use `<thead>`, though it has styles defined? I've used it in some places, because I thought it looked nicer. I can make these plain tables again, no problem.

@ellduin can answer this one.

> * You also don't seem to use `<br/>` in tables. Are they frowned upon?

`<br>` is used a lot. @ellduin told me modern HTML uses `<br>`, not `<br/>`.

> * I don't really like the look of the "Die Bedeutungen der Gerätenummern" tables in "Komfortables Treiberprogramm für Centronics-Drucker". (But the layout of the printed table is weird, too, imho). Do you have any suggestion?

I would have done it the same way. Fine! :)

**Comment by mist64** [comment]
I'll merge this now, you can always open new pull requests for additional work!

**Comment by ellduin** [comment]
> > * Seems you never use `<thead>`, though it has styles defined? I've used it in some places, because I thought it looked nicer. I can make these plain tables again, no problem.
> 
> @ellduin can answer this one.

It is used rarely (only 84/04 so far) - go ahead and use it more :D 

https://www.64er-magazin.de/8404/expansions.html
https://www.64er-magazin.de/8404/drawline.html
https://www.64er-magazin.de/8404/drucker.html

A lot of the tables are harder to put into a thead + tbody, so there is a "separator" class for th elements that does the same
`<th colspan="2" class="separator">Programmierhilfen</th>`
eg:
https://www.64er-magazin.de/8404/invaders.html

I think i went through 84/04 and added both versions, but I have not done the same for the later issues. 

> > * You also don't seem to use `<br/>` in tables. Are they frowned upon?
> 
> `<br>` is used a lot. @ellduin told me modern HTML uses `<br>`, not `<br/>`.

no frowning! 

I moved away from the <br/> with trailing slashes because I like to validate the HTML and the validator is unhappy with trailing slashes for standalone attributes (it is not a good thing anymore it seems)

**Comment by thierer** [comment]
> A lot of the tables are harder to put into a thead + tbody, so there is a "separator" class for th elements that does the same
> `<th colspan="2" class="separator">Programmierhilfen</th>`
> eg:
> https://www.64er-magazin.de/8404/invaders.html

That's useful, thanks for the hint!

> I moved away from the `<br/>` with trailing slashes because I like to validate the HTML and the validator is unhappy with trailing slashes for standalone attributes (it is not a good thing anymore it seems)

I actually thought so too, but I checked MDN, and there [all the examples use `<br />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br). [This SO thread](https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br) doesn't have a conclusive answer, imho, either :shrug:. Anyway, [7b739b7](https://github.com/mist64/64er-magazin.de/pull/61/commits/7b739b7aee7430191b6fec0c91f188c4dbd19962) replaces my `<br/>`s with `<br>`.

**Pull request merged**
