### PR TITLE
More 8407 content

### PR DESCRIPTION
**Pull request by thierer**
- Result of proof-reading the remaining articles
- added `64er.index_title` and `64er.index_category`

Some remarks for the latter:
- Some index entries include a "(nur auf Disk)" remark in the title. I omitted these from the tags. But I did include remarks like "(LdM)", "(VC 20)", ...
- Some entries don't match the title of the actual title (e.g. "Space Invaders" (page 81) is "Space Invader" in the index and "Lode Runner" (page 69) is spelled "Loderunner" in the index. In all these cases I nevertheless used the spelling from the index.
- There's a lone index entry for the "Tips & Tricks" sub-entry "Vom Bildschirm auf Kassette/Diskette" on page 135. I'm not sure how this should be handled? It's part of [135 Tips & Tricks.html](https://github.com/mist64/64er-magazin.de/blob/issue8407/issues/8407/135%20Tips%20%26%20Tricks.html), should it be added as a tag there if though it only refers to one part of that article?
- Some article have multiple entries in the index ([Terminalprogramm für den C 64](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/24%20Terminalprogramm%20f%C3%BCr%20den%20C%2064.html) and [Adressenvergleich VC 20-C64](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/52%20Der%20Volkscomputer%20und%20der%20gro%C3%9Fe%20Bruder-%20Adressenvergleich%20VC%2020%20-%20C%2064.html)). For these I added [multiple `64er.index_category` tags](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/24%20Terminalprogramm%20f%C3%BCr%20den%20C%2064.html#L15-L16). Is this correct?
- Some articles are not referenced by the index. The previous issues suggest that these should have their tags removed completely. I haven't done that yet.

### CODE REVIEW

**Comment by mist64** [comment]
> * Result of proof-reading the remaining articles
> * added `64er.index_title` and `64er.index_category`

Whoa, awesome! :) :)

> * Some index entries include a "(nur auf Disk)" remark in the title. I omitted these from the tags. But I did include remarks like "(LdM)", "(VC 20)", ...

Good!

> * Some entries don't match the title of the actual title (e.g. "Space Invaders" (page 81) is "Space Invader" in the index and "Lode Runner" (page 69) is spelled "Loderunner" in the index. In all these cases I nevertheless used the spelling from the index.

We haven't had this case yet and I have no strong opinions. Yes, let's use the literal version from the index.

> * There's a lone index entry for the "Tips & Tricks" sub-entry "Vom Bildschirm auf Kassette/Diskette" on page 135. I'm not sure how this should be handled? It's part of [135 Tips & Tricks.html](https://github.com/mist64/64er-magazin.de/blob/issue8407/issues/8407/135%20Tips%20%26%20Tricks.html), should it be added as a tag there if though it only refers to one part of that article?

Ah, my bad. I treated "Vom Bildschirm auf Kassette/Diskette" as a section of the "Tips & Tricks" article, but it should be its own article. I'll split it into a separate HTML in a followup change.

> * Some article have multiple entries in the index ([Terminalprogramm für den C 64](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/24%20Terminalprogramm%20f%C3%BCr%20den%20C%2064.html) and [Adressenvergleich VC 20-C64](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/52%20Der%20Volkscomputer%20und%20der%20gro%C3%9Fe%20Bruder-%20Adressenvergleich%20VC%2020%20-%20C%2064.html)). For these I added [multiple `64er.index_category` tags](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/24%20Terminalprogramm%20f%C3%BCr%20den%20C%2064.html#L15-L16). Is this correct?

I am not sure HTML allows this, and I any case, I don't think it's useful. "Software" is the wrong category, so I think this is a mistake in the index that they added it twice, once to correct category and once to an incorrect category.

> * Some articles are not referenced by the index. The previous issues suggest that these should have their tags removed completely. I haven't done that yet.

Yes, no tags there.

I'll merge it as is, we can iterate on top. :)

**Comment by mist64** [comment]
Curious that the Forth article and the Tips & Tricks article are not in the index. That's a mistake and I think we should add them.

**Comment by mist64** [comment]
I removed the duplicate categories, removed all "XXX" categories except "Forth" and "Tips & Tricks" (TODO) and moved "Vom Bildschirm auf Kassette/Diskette" into its own article.

**Comment by mist64** [comment]
I think this concludes everything I wanted to do on top of your changes.

Thanks again!! :)

**Comment by thierer** [comment]
> * Ah, the Forth article is in fact in the index, as "Software|Sprachen". Added.

Right, sorry, I missed that.



> > * Some article have multiple entries in the index ([Terminalprogramm für den C 64](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/24%20Terminalprogramm%20f%C3%BCr%20den%20C%2064.html) and [Adressenvergleich VC 20-C64](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/52%20Der%20Volkscomputer%20und%20der%20gro%C3%9Fe%20Bruder-%20Adressenvergleich%20VC%2020%20-%20C%2064.html)). For these I added [multiple `64er.index_category` tags](https://github.com/thierer/64er-magazin.de/blob/7453db1979764e73e1cb499e0b3e1b41ab551ae6/issues/8407/24%20Terminalprogramm%20f%C3%BCr%20den%20C%2064.html#L15-L16). Is this correct?
> 
> I am not sure HTML allows this, and I any case, I don't think it's useful. "Software" is the wrong category, so I think this is a mistake in the index that they added it twice, once to correct category and once to an incorrect category.

I don't know, "Software" is used rather broad, it includes both topics about ready-made software and about programming. But I made a mistake with the category, it's actually "Software|Adressenvergleich", not "Software|Transfer". I'll go through the categories again over the weekend in case I made more mistakes...

And imho it might be useful to include entries under multiple topics. Regarding multiple `<meta>` tags: I'm not sure, but I guess "HTML" doesn't care. It's up to the software reading it what to make of them. Another option instead of duplication might be to use a comma-separated list, like for "keywords".

> * "Tips & Tricks" was missing from both the TOC and the index, which I consider a mistake we should fix, I added it like this:
> [...]
>     `<meta name="64er.index_category" content="Listings zum Abtippen|Tips &amp; Tricks|Tips &amp; Tricks"> <!-- was missing from index -->`

Are you sure that the entity encoding is appropriate inside the quoted text? Except if they are copied verbatim into HTML content - but I guess that would then affect `64er.index_category` tags in other articles as well.

**Pull request merged**
